on:
  workflow_dispatch:
  schedule:
    - cron: '45 2,6,10 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-c3@cron
        with:
          token: ${{ secrets.token }}
